### Get index to prove that the server is running
GET {{ baseUrl }}:{{port}}/


###Get a list of all products
GET {{ baseUrl }}:{{port}}/products

### Create a product
POST {{ baseUrl }}:{{port}}/products
Content-Type: application/json

{
  "name": "iMac Air desde docker",
  "price": 2900
}


### GET a product by id
GET {{ baseUrl }}:{{port}}/products/6467ac7a9673cd507e526ffd


### Update a product by id
PATCH {{ baseUrl }}:{{port}}/products/6467aa2a9673cd507e526ffa
Content-Type: application/json

{
  "price": 5999
}


### Delete a product by id
DELETE  {{ baseUrl }}:{{port}}/products/6467bf9b74f78b001254ac0a


### 404 route Not Found
GET {{ baseUrl }}:{{port}}/abc_xyz



































#hrXWgw4Q127uqZJ3